#!/usr/bin/sh

# author GG weebcyberpunk@gmail.com
# version 0.0.0
# since Mar 25, 2022

# installs my enviroment
# ...
# nothing more to say about it
#
# needs to be run as root inside the cloned repo

# LIB {{{
# prints error msg and exits
function error {
	echo "$1"
	exit 1
}

# }}}

# CONFIGURE {{{

# username
function getusername {
	USERNAME=$(
		dialog \
		--title "User config" \
		--inputbox "Please enter the username to user GG's IDLE. If the user don't exists, the script will create it.\n
	If it exists, some config files will be overwritten." \
		0 0 \
		3>&1 1>&2 2>&3 3>&1
	)
	if [ "$USERNAME" == "1" ]
	then
		error "User exited"
	fi

	while ! echo $USERNAME | grep -q "^[a-z_][a-z0-9_-]*$"; do
		USERNAME=$(
		dialog \
		--inputbox "Invalid username. Remember that usernames needs to be only lowercase letters, _ and - and start with a letter" \
		0 0 \
		3>&1 1>&2 2>&3 3>&1
		)
		if [ "$USERNAME" == "1" ]
		then
			error "User exited"
		fi
	done
}

# wallpapers path
function wallpapersconfig {
	WALLPAPERS_PATH=$(dialog \
		--menu "Choose directory to install the IDLE wallpapers: " \
		0 0 0 \
		"/usr/share/backgrounds/Wallpapers" "Recommended, accessible system-wide" \
		"~/Pictures/Wallpapers" "Accessible only by the $USERNAME user" \
		3>&1 1>&2 2>&3 3>&1
	)
}

# }}}

# MAKE {{{

# perform full sys upgrade
function sysupgrade {
	echo 'Performing full system upgrade...'
	pacman -Syu --noconfirm > /dev/null 2>&1 || error "Cannot upgrade system. Are you sure you are running this from an Arch-based GNU/Linux distribution, is root and have internet connection?"
	echo 'Installing dialog to use it during the script'
	pacman -S --needed --noconfirm dialog > /dev/null 2>&1
}

# }}}

sysupgrade
getusername
wallpapersconfig
