#!/usr/bin/sh

# author GG weebcyberpunk@gmail.com
# version 0.0.0
# since Mar 25, 2022

# installs my enviroment
# ...
# nothing more to say about it
#
# needs to be run as root inside the cloned repo

# prints error msg and exits
function error {
	echo "$1"
	exit 1
}

# perform full sys upgrade
echo 'Performing system upgrade...'
pacman -Syu --noconfirm > /dev/null 2>&1 || error "Cannot upgrade system. Are you sure you are running this from an Arch-based GNU/Linux distribution and have internet connection?"
echo 'Installing dialog to use it during the script'
pacman -S --needed dialog >> /dev/null

# CONFIGURE {{{

# username
USERNAME=$(
	dialog \
	--title "Welcome to the GG's IDLE install!" \
	--inputbox "Please enter the username to user GG's IDLE. If the user don't exists, the script will create it.\n
If it exists, some config files will be overwritten." \
	10 60 \
	3>&1 1>&2 2>&3 3>&1
)

while ! echo $USERNAME | grep -q "^[a-z_][a-z0-9_-]*$"; do
	USERNAME=$(
	dialog \
	--inputbox "Invalid username. Remember that usernames needs to be only lowercase letters, _ and - and start with a letter" \
	10 60 \
	3>&1 1>&2 2>&3 3>&1
	)
done

# wallpapers path
WALLPAPERS_PATH=$(dialog \
	--menu "Choose directory to install the IDLE wallpapers: " \
	10 80 80 \
	"/usr/share/backgrounds/Wallpapers" "Recommended, accessible system-wide" \
	"~/Pictures/Wallpapers" "Accessible only by the $USERNAME user" \
	3>&1 1>&2 2>&3 3>&1
)

# }}}

# MAKE {{{
exit
if [ "$(cat /etc/passwd | grep $USERNAME)" == "" ]
then
	echo "Detected that user $USERNAME don't exist."
	echo "GG's IDLE will create user $USERNAME."
	echo -n "CONTINUE? [y/N] "
	read CONTINUE
	if [ "CONTINUE" != "y" ]
	useradd -m -G games,floppy,scanner,video,storage,optical,input,disk,wheel $USERNAME
	echo "Enter password for the new user: "
	passwd $USERNAME

else
	echo "Detected that user $USERNAME EXISTS. The IDLE install script will override some config files of the user."
	echo -n "CONTINUE? [y/N] "
	if [ $(read)]

# }}}
