.TH GGIDLE\ KEYBOARD\ SHORTCUTS 7 ggidle

.SH NAME

GG's IDLE \- Using keyboard shortcuts

.SH INTRO

Everything in GG's IDLE is keyboard-driven and for most things you simply can't use the mouse.

.SH LIST

.SS DWM COMMON OPERATIONS
.TP
.B Super + a
spawns dmenu with the dmenu_run script
.TP
.B Super + Enter
spawns a terminal (default: st). OBS: please DO NOT FUCKING uninstall ST
.TP
.B Super + Ctrl + b
toggles on/off the DWM panel
.TP
.B Super + j
focus previous window in DWM stack
.TP
.B Super + k
focus next window in DWM stack
.TP
.B Super + Shift + j
rotates master or slave area
.TP
.B Super + Shift + k
rotates master or slave area (reversed)
.TP
.B Super + Shift + h
increases master area
.TP
.B Super + Shift + l
shrinks master area
.TP
.B Super + Shift + Enter
swaps window with master
.TP
.B Ctrl + Shift + Tab
go to last used workspace
.TP
.B Super + w
kills window
.TP
.B Super + Ctrl + t
select tilling layout
.TP
.B Super + Ctrl + f
select floating layout
.TP
.B Super + Ctrl + m
select monocle layout
.TP
