.TH GGIDLE\ STYLE 7

.SH NAME

GG's IDLE appearance \- aesthetics of the desktop enviroment

.SH GENERAL

The GG's IDLE GTK theme is Flat Remix Dark and the default variation is blue. QT is configured with the package qt5-styleplugins and the enviroment variable in the file $HOME/.pam_enviroment to mimic the GTK appearance, and applications with specific appearance configs (ex: Qutebrowser, Zathura and dmenu) all are configured to match the Flat Remix Dark theme.

Therefore, all the desktop have the same look and feel.

.SH CONFIGURE

The easiest way to change the desktop look and feel is changing the Flat Remix Dark theme variation. GG's IDLE install an script called idle-color-chooser that automatically configure all IDLE applications and recompile suckless programs to use an user-selected color variation from the Flat Remix Dark collection. Learn more with
.B man\ idle-color-chooser\fR.

However, blue is choosed to be the default because of two reasons: 1) It's GG's favorite color and 2) Most terminal-based applications use blue as the main color.

If you want to configure look and feel manually, set gtk themes in $HOME/.pam_enviroment, $HOME/.gtkrc-2.0, $HOME/.config/gtk-3.0/settings.ini and specific configuration on each program config file (or source, if it's a suckless program).
