.TH GGIDLE\ TMUX\ CONFIGS 7

.SH NAME
Tmux - A terminal multiplexer, IDLE configs.

.SH KEYBINDS

The tmux prefix is setted to Ctrl-a because everyone agrees it's the best default.

The navigation keys are setted to Alt-hjkl so they do not conflict with Vim windows navigation keys.

Prefix with i and u will split the window horizontally and vertically.

Prefix and F5 will reload the config file.

.SH GENERAL

Other configs are just setting the shell to zsh and aesthetic configs.
