.TH GGIDLE\ CMUS\ CONFIGS 7

.SH NAME
Cmus - GG's configuration for a Ncurses music player.

.SH GENERAL
3 of the 4 lines of the cmus' rc are just good defaults. Cmus do not sets the window title on GG's IDLE just to avoid massive window titles.

Also, the lastline sets Cmus to run the cmus_change_status.sh script every time it changes the player status (i.e., changes song, pauses, etc). This script will sends a short notification with the song info and update the DWM's statusbar.
